//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 02:00:14 PM MDT 
//


package gme.cacore_cacore._4_4.edu_northwestern_radiology;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gme.cacore_cacore._4_4.edu_northwestern_radiology package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ImageAnnotationCollection_QNAME = new QName("gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", "ImageAnnotationCollection");
    private final static QName _AnnotationOfAnnotationCollection_QNAME = new QName("gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", "AnnotationOfAnnotationCollection");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gme.cacore_cacore._4_4.edu_northwestern_radiology
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ThreeDimensionGeometricShapeEntityIsComprisedOfThreeDimensionGeometricShapeEntityStatement }
     * 
     */
    public ThreeDimensionGeometricShapeEntityIsComprisedOfThreeDimensionGeometricShapeEntityStatement createThreeDimensionGeometricShapeEntityIsComprisedOfThreeDimensionGeometricShapeEntityStatement() {
        return new ThreeDimensionGeometricShapeEntityIsComprisedOfThreeDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntity.ImagingPhysicalEntityCharacteristicCollection }
     * 
     */
    public ImagingPhysicalEntity.ImagingPhysicalEntityCharacteristicCollection createImagingPhysicalEntityImagingPhysicalEntityCharacteristicCollection() {
        return new ImagingPhysicalEntity.ImagingPhysicalEntityCharacteristicCollection();
    }

    /**
     * Create an instance of {@link ImageAnnotation }
     * 
     */
    public ImageAnnotation createImageAnnotation() {
        return new ImageAnnotation();
    }

    /**
     * Create an instance of {@link ImageAnnotation.MarkupEntityCollection }
     * 
     */
    public ImageAnnotation.MarkupEntityCollection createImageAnnotationMarkupEntityCollection() {
        return new ImageAnnotation.MarkupEntityCollection();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationHasTimePointLesionObservationEntityStatement }
     * 
     */
    public AnnotationOfAnnotationHasTimePointLesionObservationEntityStatement createAnnotationOfAnnotationHasTimePointLesionObservationEntityStatement() {
        return new AnnotationOfAnnotationHasTimePointLesionObservationEntityStatement();
    }

    /**
     * Create an instance of {@link Interval }
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link CalculationData }
     * 
     */
    public CalculationData createCalculationData() {
        return new CalculationData();
    }

    /**
     * Create an instance of {@link ExtendedCalculationResult.CalculationDataCollection }
     * 
     */
    public ExtendedCalculationResult.CalculationDataCollection createExtendedCalculationResultCalculationDataCollection() {
        return new ExtendedCalculationResult.CalculationDataCollection();
    }

    /**
     * Create an instance of {@link ImagingObservationEntityIsIdentifiedByTextAnnotationEntityStatement }
     * 
     */
    public ImagingObservationEntityIsIdentifiedByTextAnnotationEntityStatement createImagingObservationEntityIsIdentifiedByTextAnnotationEntityStatement() {
        return new ImagingObservationEntityIsIdentifiedByTextAnnotationEntityStatement();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationHasGeneralLesionObservationEntityStatement }
     * 
     */
    public AnnotationOfAnnotationHasGeneralLesionObservationEntityStatement createAnnotationOfAnnotationHasGeneralLesionObservationEntityStatement() {
        return new AnnotationOfAnnotationHasGeneralLesionObservationEntityStatement();
    }

    /**
     * Create an instance of {@link ExtendedCalculationResult }
     * 
     */
    public ExtendedCalculationResult createExtendedCalculationResult() {
        return new ExtendedCalculationResult();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.InferenceEntityCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.InferenceEntityCollection createAnnotationEntityInferenceEntityCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.InferenceEntityCollection();
    }

    /**
     * Create an instance of {@link InferenceEntity }
     * 
     */
    public InferenceEntity createInferenceEntity() {
        return new InferenceEntity();
    }

    /**
     * Create an instance of {@link GeneralLesionObservationEntity }
     * 
     */
    public GeneralLesionObservationEntity createGeneralLesionObservationEntity() {
        return new GeneralLesionObservationEntity();
    }

    /**
     * Create an instance of {@link TwoDimensionSpatialCoordinate }
     * 
     */
    public TwoDimensionSpatialCoordinate createTwoDimensionSpatialCoordinate() {
        return new TwoDimensionSpatialCoordinate();
    }

    /**
     * Create an instance of {@link Scale }
     * 
     */
    public Scale createScale() {
        return new Scale();
    }

    /**
     * Create an instance of {@link DicomSegmentationEntityHasImagingObservationEntityStatement }
     * 
     */
    public DicomSegmentationEntityHasImagingObservationEntityStatement createDicomSegmentationEntityHasImagingObservationEntityStatement() {
        return new DicomSegmentationEntityHasImagingObservationEntityStatement();
    }

    /**
     * Create an instance of {@link TaskContextEntity }
     * 
     */
    public TaskContextEntity createTaskContextEntity() {
        return new TaskContextEntity();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationHasImagingPhysicalEntityStatement }
     * 
     */
    public AnnotationOfAnnotationHasImagingPhysicalEntityStatement createAnnotationOfAnnotationHasImagingPhysicalEntityStatement() {
        return new AnnotationOfAnnotationHasImagingPhysicalEntityStatement();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.AnnotationRoleEntityCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.AnnotationRoleEntityCollection createAnnotationEntityAnnotationRoleEntityCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.AnnotationRoleEntityCollection();
    }

    /**
     * Create an instance of {@link CalculationEntityUsesCalculationEntityStatement }
     * 
     */
    public CalculationEntityUsesCalculationEntityStatement createCalculationEntityUsesCalculationEntityStatement() {
        return new CalculationEntityUsesCalculationEntityStatement();
    }

    /**
     * Create an instance of {@link ImagingObservationEntity.ImagingObservationCharacteristicCollection }
     * 
     */
    public ImagingObservationEntity.ImagingObservationCharacteristicCollection createImagingObservationEntityImagingObservationCharacteristicCollection() {
        return new ImagingObservationEntity.ImagingObservationCharacteristicCollection();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasCalculationEntityStatement }
     * 
     */
    public ImageAnnotationHasCalculationEntityStatement createImageAnnotationHasCalculationEntityStatement() {
        return new ImageAnnotationHasCalculationEntityStatement();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntityCharacteristic }
     * 
     */
    public ImagingPhysicalEntityCharacteristic createImagingPhysicalEntityCharacteristic() {
        return new ImagingPhysicalEntityCharacteristic();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasTextAnnotationEntityStatement }
     * 
     */
    public ImageAnnotationHasTextAnnotationEntityStatement createImageAnnotationHasTextAnnotationEntityStatement() {
        return new ImageAnnotationHasTextAnnotationEntityStatement();
    }

    /**
     * Create an instance of {@link CompactCalculationResult }
     * 
     */
    public CompactCalculationResult createCompactCalculationResult() {
        return new CompactCalculationResult();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationIsComparedWithImageAnnotationStatement }
     * 
     */
    public AnnotationOfAnnotationIsComparedWithImageAnnotationStatement createAnnotationOfAnnotationIsComparedWithImageAnnotationStatement() {
        return new AnnotationOfAnnotationIsComparedWithImageAnnotationStatement();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasImagingObservationEntityStatement }
     * 
     */
    public ImageAnnotationHasImagingObservationEntityStatement createImageAnnotationHasImagingObservationEntityStatement() {
        return new ImageAnnotationHasImagingObservationEntityStatement();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasDicomSegmentationEntityStatement }
     * 
     */
    public ImageAnnotationHasDicomSegmentationEntityStatement createImageAnnotationHasDicomSegmentationEntityStatement() {
        return new ImageAnnotationHasDicomSegmentationEntityStatement();
    }

    /**
     * Create an instance of {@link UriImageReferenceEntityHasImagingPhysicalEntityStatement }
     * 
     */
    public UriImageReferenceEntityHasImagingPhysicalEntityStatement createUriImageReferenceEntityHasImagingPhysicalEntityStatement() {
        return new UriImageReferenceEntityHasImagingPhysicalEntityStatement();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.CalculationResult.DimensionCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.CalculationResult.DimensionCollection createCalculationResultDimensionCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.CalculationResult.DimensionCollection();
    }

    /**
     * Create an instance of {@link ThreeDimensionEllipsoid }
     * 
     */
    public ThreeDimensionEllipsoid createThreeDimensionEllipsoid() {
        return new ThreeDimensionEllipsoid();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationCollection }
     * 
     */
    public AnnotationOfAnnotationCollection createAnnotationOfAnnotationCollection() {
        return new AnnotationOfAnnotationCollection();
    }

    /**
     * Create an instance of {@link ThreeDimensionPoint }
     * 
     */
    public ThreeDimensionPoint createThreeDimensionPoint() {
        return new ThreeDimensionPoint();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntity.ImagingObservationCharacteristicCollection }
     * 
     */
    public ImagingPhysicalEntity.ImagingObservationCharacteristicCollection createImagingPhysicalEntityImagingObservationCharacteristicCollection() {
        return new ImagingPhysicalEntity.ImagingObservationCharacteristicCollection();
    }

    /**
     * Create an instance of {@link ImagePlane }
     * 
     */
    public ImagePlane createImagePlane() {
        return new ImagePlane();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntityCharacteristic.CharacteristicQuantificationCollection }
     * 
     */
    public ImagingPhysicalEntityCharacteristic.CharacteristicQuantificationCollection createImagingPhysicalEntityCharacteristicCharacteristicQuantificationCollection() {
        return new ImagingPhysicalEntityCharacteristic.CharacteristicQuantificationCollection();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.ImagingPhysicalEntityCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.ImagingPhysicalEntityCollection createAnnotationEntityImagingPhysicalEntityCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.ImagingPhysicalEntityCollection();
    }

    /**
     * Create an instance of {@link ImageSeries.ImageCollection }
     * 
     */
    public ImageSeries.ImageCollection createImageSeriesImageCollection() {
        return new ImageSeries.ImageCollection();
    }

    /**
     * Create an instance of {@link Coordinate }
     * 
     */
    public Coordinate createCoordinate() {
        return new Coordinate();
    }

    /**
     * Create an instance of {@link Algorithm }
     * 
     */
    public Algorithm createAlgorithm() {
        return new Algorithm();
    }

    /**
     * Create an instance of {@link DicomImageReferenceEntity }
     * 
     */
    public DicomImageReferenceEntity createDicomImageReferenceEntity() {
        return new DicomImageReferenceEntity();
    }

    /**
     * Create an instance of {@link ImageAnnotation.ImageReferenceEntityCollection }
     * 
     */
    public ImageAnnotation.ImageReferenceEntityCollection createImageAnnotationImageReferenceEntityCollection() {
        return new ImageAnnotation.ImageReferenceEntityCollection();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link ImageStudy.ReferencedDicomObjectCollection }
     * 
     */
    public ImageStudy.ReferencedDicomObjectCollection createImageStudyReferencedDicomObjectCollection() {
        return new ImageStudy.ReferencedDicomObjectCollection();
    }

    /**
     * Create an instance of {@link UriImageReferenceEntityHasImagingObservationEntityStatement }
     * 
     */
    public UriImageReferenceEntityHasImagingObservationEntityStatement createUriImageReferenceEntityHasImagingObservationEntityStatement() {
        return new UriImageReferenceEntityHasImagingObservationEntityStatement();
    }

    /**
     * Create an instance of {@link ImageAnnotationCollection }
     * 
     */
    public ImageAnnotationCollection createImageAnnotationCollection() {
        return new ImageAnnotationCollection();
    }

    /**
     * Create an instance of {@link ThreeDimensionPolygon }
     * 
     */
    public ThreeDimensionPolygon createThreeDimensionPolygon() {
        return new ThreeDimensionPolygon();
    }

    /**
     * Create an instance of {@link ImagingObservationEntityIsIdentifiedByTwoDimensionGeometricShapeEntityStatement }
     * 
     */
    public ImagingObservationEntityIsIdentifiedByTwoDimensionGeometricShapeEntityStatement createImagingObservationEntityIsIdentifiedByTwoDimensionGeometricShapeEntityStatement() {
        return new ImagingObservationEntityIsIdentifiedByTwoDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link CalculationEntityIsComparedWithCalculationEntityStatement }
     * 
     */
    public CalculationEntityIsComparedWithCalculationEntityStatement createCalculationEntityIsComparedWithCalculationEntityStatement() {
        return new CalculationEntityIsComparedWithCalculationEntityStatement();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasTimePointLesionObservationEntityStatement }
     * 
     */
    public ImageAnnotationHasTimePointLesionObservationEntityStatement createImageAnnotationHasTimePointLesionObservationEntityStatement() {
        return new ImageAnnotationHasTimePointLesionObservationEntityStatement();
    }

    /**
     * Create an instance of {@link CalculationEntityReferencesCalculationEntityStatement }
     * 
     */
    public CalculationEntityReferencesCalculationEntityStatement createCalculationEntityReferencesCalculationEntityStatement() {
        return new CalculationEntityReferencesCalculationEntityStatement();
    }

    /**
     * Create an instance of {@link TextAnnotationEntity }
     * 
     */
    public TextAnnotationEntity createTextAnnotationEntity() {
        return new TextAnnotationEntity();
    }

    /**
     * Create an instance of {@link ImageAnnotation.ImageAnnotationStatementCollection }
     * 
     */
    public ImageAnnotation.ImageAnnotationStatementCollection createImageAnnotationImageAnnotationStatementCollection() {
        return new ImageAnnotation.ImageAnnotationStatementCollection();
    }

    /**
     * Create an instance of {@link ImageAnnotationIsComparedWithAnnotationOfAnnotationStatement }
     * 
     */
    public ImageAnnotationIsComparedWithAnnotationOfAnnotationStatement createImageAnnotationIsComparedWithAnnotationOfAnnotationStatement() {
        return new ImageAnnotationIsComparedWithAnnotationOfAnnotationStatement();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntityHasTwoDimensionGeometricShapeEntityStatement }
     * 
     */
    public ImagingPhysicalEntityHasTwoDimensionGeometricShapeEntityStatement createImagingPhysicalEntityHasTwoDimensionGeometricShapeEntityStatement() {
        return new ImagingPhysicalEntityHasTwoDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.CalculationEntityCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.CalculationEntityCollection createAnnotationEntityCalculationEntityCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.CalculationEntityCollection();
    }

    /**
     * Create an instance of {@link ReferencedDicomObject }
     * 
     */
    public ReferencedDicomObject createReferencedDicomObject() {
        return new ReferencedDicomObject();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasInferenceEntityStatement }
     * 
     */
    public ImageAnnotationHasInferenceEntityStatement createImageAnnotationHasInferenceEntityStatement() {
        return new ImageAnnotationHasInferenceEntityStatement();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationIsComparedWithAnnotationOfAnnotationStatement }
     * 
     */
    public AnnotationOfAnnotationIsComparedWithAnnotationOfAnnotationStatement createAnnotationOfAnnotationIsComparedWithAnnotationOfAnnotationStatement() {
        return new AnnotationOfAnnotationIsComparedWithAnnotationOfAnnotationStatement();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.AuditTrailCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.AuditTrailCollection createAnnotationEntityAuditTrailCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.AuditTrailCollection();
    }

    /**
     * Create an instance of {@link NonQuantifiable }
     * 
     */
    public NonQuantifiable createNonQuantifiable() {
        return new NonQuantifiable();
    }

    /**
     * Create an instance of {@link TwoDimensionMultiPoint }
     * 
     */
    public TwoDimensionMultiPoint createTwoDimensionMultiPoint() {
        return new TwoDimensionMultiPoint();
    }

    /**
     * Create an instance of {@link CalculationEntity }
     * 
     */
    public CalculationEntity createCalculationEntity() {
        return new CalculationEntity();
    }

    /**
     * Create an instance of {@link DicomImageReferenceEntityHasImagingObservationEntityStatement }
     * 
     */
    public DicomImageReferenceEntityHasImagingObservationEntityStatement createDicomImageReferenceEntityHasImagingObservationEntityStatement() {
        return new DicomImageReferenceEntityHasImagingObservationEntityStatement();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link UriImageReferenceEntity }
     * 
     */
    public UriImageReferenceEntity createUriImageReferenceEntity() {
        return new UriImageReferenceEntity();
    }

    /**
     * Create an instance of {@link CalculationEntity.CalculationResultCollection }
     * 
     */
    public CalculationEntity.CalculationResultCollection createCalculationEntityCalculationResultCollection() {
        return new CalculationEntity.CalculationResultCollection();
    }

    /**
     * Create an instance of {@link DicomImageReferenceEntityHasImagingPhysicalEntityStatement }
     * 
     */
    public DicomImageReferenceEntityHasImagingPhysicalEntityStatement createDicomImageReferenceEntityHasImagingPhysicalEntityStatement() {
        return new DicomImageReferenceEntityHasImagingPhysicalEntityStatement();
    }

    /**
     * Create an instance of {@link ImagingObservationEntityHasCalculationEntityStatement }
     * 
     */
    public ImagingObservationEntityHasCalculationEntityStatement createImagingObservationEntityHasCalculationEntityStatement() {
        return new ImagingObservationEntityHasCalculationEntityStatement();
    }

    /**
     * Create an instance of {@link GeneralImage }
     * 
     */
    public GeneralImage createGeneralImage() {
        return new GeneralImage();
    }

    /**
     * Create an instance of {@link TwoDimensionCircle }
     * 
     */
    public TwoDimensionCircle createTwoDimensionCircle() {
        return new TwoDimensionCircle();
    }

    /**
     * Create an instance of {@link ThreeDimensionMultiPoint }
     * 
     */
    public ThreeDimensionMultiPoint createThreeDimensionMultiPoint() {
        return new ThreeDimensionMultiPoint();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntityHasThreeDimensionGeometricShapeEntityStatement }
     * 
     */
    public ImagingPhysicalEntityHasThreeDimensionGeometricShapeEntityStatement createImagingPhysicalEntityHasThreeDimensionGeometricShapeEntityStatement() {
        return new ImagingPhysicalEntityHasThreeDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link DicomImageReferenceEntityHasCalculationEntityStatement }
     * 
     */
    public DicomImageReferenceEntityHasCalculationEntityStatement createDicomImageReferenceEntityHasCalculationEntityStatement() {
        return new DicomImageReferenceEntityHasCalculationEntityStatement();
    }

    /**
     * Create an instance of {@link Quantile }
     * 
     */
    public Quantile createQuantile() {
        return new Quantile();
    }

    /**
     * Create an instance of {@link ImagingObservationCharacteristic.CharacteristicQuantificationCollection }
     * 
     */
    public ImagingObservationCharacteristic.CharacteristicQuantificationCollection createImagingObservationCharacteristicCharacteristicQuantificationCollection() {
        return new ImagingObservationCharacteristic.CharacteristicQuantificationCollection();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasGeneralLesionObservationEntityStatement }
     * 
     */
    public ImageAnnotationHasGeneralLesionObservationEntityStatement createImageAnnotationHasGeneralLesionObservationEntityStatement() {
        return new ImageAnnotationHasGeneralLesionObservationEntityStatement();
    }

    /**
     * Create an instance of {@link Algorithm.ParameterCollection }
     * 
     */
    public Algorithm.ParameterCollection createAlgorithmParameterCollection() {
        return new Algorithm.ParameterCollection();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationHasImageAnnotationStatement }
     * 
     */
    public AnnotationOfAnnotationHasImageAnnotationStatement createAnnotationOfAnnotationHasImageAnnotationStatement() {
        return new AnnotationOfAnnotationHasImageAnnotationStatement();
    }

    /**
     * Create an instance of {@link TwoDimensionEllipse }
     * 
     */
    public TwoDimensionEllipse createTwoDimensionEllipse() {
        return new TwoDimensionEllipse();
    }

    /**
     * Create an instance of {@link ImagingObservationEntityIsIdentifiedByThreeDimensionGeometricShapeEntityStatement }
     * 
     */
    public ImagingObservationEntityIsIdentifiedByThreeDimensionGeometricShapeEntityStatement createImagingObservationEntityIsIdentifiedByThreeDimensionGeometricShapeEntityStatement() {
        return new ImagingObservationEntityIsIdentifiedByThreeDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationHasCalculationEntityStatement }
     * 
     */
    public AnnotationOfAnnotationHasCalculationEntityStatement createAnnotationOfAnnotationHasCalculationEntityStatement() {
        return new AnnotationOfAnnotationHasCalculationEntityStatement();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.TaskContextEntityCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.TaskContextEntityCollection createAnnotationEntityTaskContextEntityCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.TaskContextEntityCollection();
    }

    /**
     * Create an instance of {@link ImageAnnotationIsComparedWithImageAnnotationStatement }
     * 
     */
    public ImageAnnotationIsComparedWithImageAnnotationStatement createImageAnnotationIsComparedWithImageAnnotationStatement() {
        return new ImageAnnotationIsComparedWithImageAnnotationStatement();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationHasImagingObservationEntityStatement }
     * 
     */
    public AnnotationOfAnnotationHasImagingObservationEntityStatement createAnnotationOfAnnotationHasImagingObservationEntityStatement() {
        return new AnnotationOfAnnotationHasImagingObservationEntityStatement();
    }

    /**
     * Create an instance of {@link ImageAnnotationCollection.ImageAnnotations }
     * 
     */
    public ImageAnnotationCollection.ImageAnnotations createImageAnnotationCollectionImageAnnotations() {
        return new ImageAnnotationCollection.ImageAnnotations();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasThreeDimensionGeometricShapeEntityStatement }
     * 
     */
    public ImageAnnotationHasThreeDimensionGeometricShapeEntityStatement createImageAnnotationHasThreeDimensionGeometricShapeEntityStatement() {
        return new ImageAnnotationHasThreeDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link ThreeDimensionEllipse }
     * 
     */
    public ThreeDimensionEllipse createThreeDimensionEllipse() {
        return new ThreeDimensionEllipse();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationCollection.AnnotationOfAnnotations }
     * 
     */
    public AnnotationOfAnnotationCollection.AnnotationOfAnnotations createAnnotationOfAnnotationCollectionAnnotationOfAnnotations() {
        return new AnnotationOfAnnotationCollection.AnnotationOfAnnotations();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationHasInferenceEntityStatement }
     * 
     */
    public AnnotationOfAnnotationHasInferenceEntityStatement createAnnotationOfAnnotationHasInferenceEntityStatement() {
        return new AnnotationOfAnnotationHasInferenceEntityStatement();
    }

    /**
     * Create an instance of {@link TimePointLesionObservationEntity }
     * 
     */
    public TimePointLesionObservationEntity createTimePointLesionObservationEntity() {
        return new TimePointLesionObservationEntity();
    }

    /**
     * Create an instance of {@link CalculationData.CoordinateCollection }
     * 
     */
    public CalculationData.CoordinateCollection createCalculationDataCoordinateCollection() {
        return new CalculationData.CoordinateCollection();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasChildImageAnnotationStatement }
     * 
     */
    public ImageAnnotationHasChildImageAnnotationStatement createImageAnnotationHasChildImageAnnotationStatement() {
        return new ImageAnnotationHasChildImageAnnotationStatement();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasDicomImageReferenceEntityStatement }
     * 
     */
    public ImageAnnotationHasDicomImageReferenceEntityStatement createImageAnnotationHasDicomImageReferenceEntityStatement() {
        return new ImageAnnotationHasDicomImageReferenceEntityStatement();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntityHasCalculationEntityStatement }
     * 
     */
    public ImagingPhysicalEntityHasCalculationEntityStatement createImagingPhysicalEntityHasCalculationEntityStatement() {
        return new ImagingPhysicalEntityHasCalculationEntityStatement();
    }

    /**
     * Create an instance of {@link ImagingObservationEntity }
     * 
     */
    public ImagingObservationEntity createImagingObservationEntity() {
        return new ImagingObservationEntity();
    }

    /**
     * Create an instance of {@link DicomSegmentationEntity }
     * 
     */
    public DicomSegmentationEntity createDicomSegmentationEntity() {
        return new DicomSegmentationEntity();
    }

    /**
     * Create an instance of {@link TaskContextEntity.TaskContextEntityCollection }
     * 
     */
    public TaskContextEntity.TaskContextEntityCollection createTaskContextEntityTaskContextEntityCollection() {
        return new TaskContextEntity.TaskContextEntityCollection();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotation.AnnotationOfAnnotationStatementCollection }
     * 
     */
    public AnnotationOfAnnotation.AnnotationOfAnnotationStatementCollection createAnnotationOfAnnotationAnnotationOfAnnotationStatementCollection() {
        return new AnnotationOfAnnotation.AnnotationOfAnnotationStatementCollection();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.ThreeDimensionGeometricShapeEntity.ThreeDimensionSpatialCoordinateCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.ThreeDimensionGeometricShapeEntity.ThreeDimensionSpatialCoordinateCollection createThreeDimensionGeometricShapeEntityThreeDimensionSpatialCoordinateCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.ThreeDimensionGeometricShapeEntity.ThreeDimensionSpatialCoordinateCollection();
    }

    /**
     * Create an instance of {@link GeneralLesionObservationEntityHasImagingPhysicalEntityStatement }
     * 
     */
    public GeneralLesionObservationEntityHasImagingPhysicalEntityStatement createGeneralLesionObservationEntityHasImagingPhysicalEntityStatement() {
        return new GeneralLesionObservationEntityHasImagingPhysicalEntityStatement();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.LesionObservationEntityCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.LesionObservationEntityCollection createAnnotationEntityLesionObservationEntityCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.LesionObservationEntityCollection();
    }

    /**
     * Create an instance of {@link ImageAnnotation.SegmentationEntityCollection }
     * 
     */
    public ImageAnnotation.SegmentationEntityCollection createImageAnnotationSegmentationEntityCollection() {
        return new ImageAnnotation.SegmentationEntityCollection();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasImagingPhysicalEntityStatement }
     * 
     */
    public ImageAnnotationHasImagingPhysicalEntityStatement createImageAnnotationHasImagingPhysicalEntityStatement() {
        return new ImageAnnotationHasImagingPhysicalEntityStatement();
    }

    /**
     * Create an instance of {@link AdjudicationObservation }
     * 
     */
    public AdjudicationObservation createAdjudicationObservation() {
        return new AdjudicationObservation();
    }

    /**
     * Create an instance of {@link ImageStudy }
     * 
     */
    public ImageStudy createImageStudy() {
        return new ImageStudy();
    }

    /**
     * Create an instance of {@link ThreeDimensionSpatialCoordinate }
     * 
     */
    public ThreeDimensionSpatialCoordinate createThreeDimensionSpatialCoordinate() {
        return new ThreeDimensionSpatialCoordinate();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link UriImageReferenceEntityHasCalculationEntityStatement }
     * 
     */
    public UriImageReferenceEntityHasCalculationEntityStatement createUriImageReferenceEntityHasCalculationEntityStatement() {
        return new UriImageReferenceEntityHasCalculationEntityStatement();
    }

    /**
     * Create an instance of {@link TwoDimensionGeometricShapeEntityExcludesTwoDimensionGeometricShapeEntityStatement }
     * 
     */
    public TwoDimensionGeometricShapeEntityExcludesTwoDimensionGeometricShapeEntityStatement createTwoDimensionGeometricShapeEntityExcludesTwoDimensionGeometricShapeEntityStatement() {
        return new TwoDimensionGeometricShapeEntityExcludesTwoDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationHasAnnotationRoleEntityStatement }
     * 
     */
    public AnnotationOfAnnotationHasAnnotationRoleEntityStatement createAnnotationOfAnnotationHasAnnotationRoleEntityStatement() {
        return new AnnotationOfAnnotationHasAnnotationRoleEntityStatement();
    }

    /**
     * Create an instance of {@link AnnotationRoleEntity }
     * 
     */
    public AnnotationRoleEntity createAnnotationRoleEntity() {
        return new AnnotationRoleEntity();
    }

    /**
     * Create an instance of {@link TwoDimensionPoint }
     * 
     */
    public TwoDimensionPoint createTwoDimensionPoint() {
        return new TwoDimensionPoint();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasTwoDimensionGeometricShapeEntityStatement }
     * 
     */
    public ImageAnnotationHasTwoDimensionGeometricShapeEntityStatement createImageAnnotationHasTwoDimensionGeometricShapeEntityStatement() {
        return new ImageAnnotationHasTwoDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.ImagingObservationEntityCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.ImagingObservationEntityCollection createAnnotationEntityImagingObservationEntityCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.AnnotationEntity.ImagingObservationEntityCollection();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntityHasTextAnnotationEntityStatement }
     * 
     */
    public ImagingPhysicalEntityHasTextAnnotationEntityStatement createImagingPhysicalEntityHasTextAnnotationEntityStatement() {
        return new ImagingPhysicalEntityHasTextAnnotationEntityStatement();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._4_4.edu_northwestern_radiology.TwoDimensionGeometricShapeEntity.TwoDimensionSpatialCoordinateCollection }
     * 
     */
    public gme.cacore_cacore._4_4.edu_northwestern_radiology.TwoDimensionGeometricShapeEntity.TwoDimensionSpatialCoordinateCollection createTwoDimensionGeometricShapeEntityTwoDimensionSpatialCoordinateCollection() {
        return new gme.cacore_cacore._4_4.edu_northwestern_radiology.TwoDimensionGeometricShapeEntity.TwoDimensionSpatialCoordinateCollection();
    }

    /**
     * Create an instance of {@link TimePointLesionObservationEntityHasImagingPhysicalEntityStatement }
     * 
     */
    public TimePointLesionObservationEntityHasImagingPhysicalEntityStatement createTimePointLesionObservationEntityHasImagingPhysicalEntityStatement() {
        return new TimePointLesionObservationEntityHasImagingPhysicalEntityStatement();
    }

    /**
     * Create an instance of {@link ImagingObservationCharacteristic }
     * 
     */
    public ImagingObservationCharacteristic createImagingObservationCharacteristic() {
        return new ImagingObservationCharacteristic();
    }

    /**
     * Create an instance of {@link Equipment }
     * 
     */
    public Equipment createEquipment() {
        return new Equipment();
    }

    /**
     * Create an instance of {@link ImagingObservationEntityIsFoundInImagingPhysicalEntityStatement }
     * 
     */
    public ImagingObservationEntityIsFoundInImagingPhysicalEntityStatement createImagingObservationEntityIsFoundInImagingPhysicalEntityStatement() {
        return new ImagingObservationEntityIsFoundInImagingPhysicalEntityStatement();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotationHasAnnotationOfAnnotationStatement }
     * 
     */
    public AnnotationOfAnnotationHasAnnotationOfAnnotationStatement createAnnotationOfAnnotationHasAnnotationOfAnnotationStatement() {
        return new AnnotationOfAnnotationHasAnnotationOfAnnotationStatement();
    }

    /**
     * Create an instance of {@link TwoDimensionPolyline }
     * 
     */
    public TwoDimensionPolyline createTwoDimensionPolyline() {
        return new TwoDimensionPolyline();
    }

    /**
     * Create an instance of {@link ThreeDimensionPolyline }
     * 
     */
    public ThreeDimensionPolyline createThreeDimensionPolyline() {
        return new ThreeDimensionPolyline();
    }

    /**
     * Create an instance of {@link AuditTrail }
     * 
     */
    public AuditTrail createAuditTrail() {
        return new AuditTrail();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotation }
     * 
     */
    public AnnotationOfAnnotation createAnnotationOfAnnotation() {
        return new AnnotationOfAnnotation();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntityHasImagingObservationEntityStatement }
     * 
     */
    public ImagingPhysicalEntityHasImagingObservationEntityStatement createImagingPhysicalEntityHasImagingObservationEntityStatement() {
        return new ImagingPhysicalEntityHasImagingObservationEntityStatement();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasUriImageReferenceEntityStatement }
     * 
     */
    public ImageAnnotationHasUriImageReferenceEntityStatement createImageAnnotationHasUriImageReferenceEntityStatement() {
        return new ImageAnnotationHasUriImageReferenceEntityStatement();
    }

    /**
     * Create an instance of {@link AnnotationEntityHasPlannedTaskContextEntityStatement }
     * 
     */
    public AnnotationEntityHasPlannedTaskContextEntityStatement createAnnotationEntityHasPlannedTaskContextEntityStatement() {
        return new AnnotationEntityHasPlannedTaskContextEntityStatement();
    }

    /**
     * Create an instance of {@link TwoDimensionGeometricShapeEntityIsComprisedOfTwoDimensionGeometricShapeEntityStatement }
     * 
     */
    public TwoDimensionGeometricShapeEntityIsComprisedOfTwoDimensionGeometricShapeEntityStatement createTwoDimensionGeometricShapeEntityIsComprisedOfTwoDimensionGeometricShapeEntityStatement() {
        return new TwoDimensionGeometricShapeEntityIsComprisedOfTwoDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link ThreeDimensionGeometricShapeEntityExcludesThreeDimensionGeometricShapeEntityStatement }
     * 
     */
    public ThreeDimensionGeometricShapeEntityExcludesThreeDimensionGeometricShapeEntityStatement createThreeDimensionGeometricShapeEntityExcludesThreeDimensionGeometricShapeEntityStatement() {
        return new ThreeDimensionGeometricShapeEntityExcludesThreeDimensionGeometricShapeEntityStatement();
    }

    /**
     * Create an instance of {@link Numerical }
     * 
     */
    public Numerical createNumerical() {
        return new Numerical();
    }

    /**
     * Create an instance of {@link ImageSeries }
     * 
     */
    public ImageSeries createImageSeries() {
        return new ImageSeries();
    }

    /**
     * Create an instance of {@link ImageAnnotationHasAnnotationRoleEntityStatement }
     * 
     */
    public ImageAnnotationHasAnnotationRoleEntityStatement createImageAnnotationHasAnnotationRoleEntityStatement() {
        return new ImageAnnotationHasAnnotationRoleEntityStatement();
    }

    /**
     * Create an instance of {@link ImagingPhysicalEntity }
     * 
     */
    public ImagingPhysicalEntity createImagingPhysicalEntity() {
        return new ImagingPhysicalEntity();
    }

    /**
     * Create an instance of {@link AnnotationEntityHasPerformedTaskContextEntityStatement }
     * 
     */
    public AnnotationEntityHasPerformedTaskContextEntityStatement createAnnotationEntityHasPerformedTaskContextEntityStatement() {
        return new AnnotationEntityHasPerformedTaskContextEntityStatement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageAnnotationCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", name = "ImageAnnotationCollection")
    public JAXBElement<ImageAnnotationCollection> createImageAnnotationCollection(ImageAnnotationCollection value) {
        return new JAXBElement<ImageAnnotationCollection>(_ImageAnnotationCollection_QNAME, ImageAnnotationCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationOfAnnotationCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", name = "AnnotationOfAnnotationCollection")
    public JAXBElement<AnnotationOfAnnotationCollection> createAnnotationOfAnnotationCollection(AnnotationOfAnnotationCollection value) {
        return new JAXBElement<AnnotationOfAnnotationCollection>(_AnnotationOfAnnotationCollection_QNAME, AnnotationOfAnnotationCollection.class, null, value);
    }

}
