//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 02:00:14 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gme.cacore_cacore._4_4.edu_northwestern_radiology;
