//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.25 at 05:00:33 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gme.cacore_cacore._3_2.edu_northwestern_radiology;
