//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.25 at 05:00:33 ÏÂÎç CST 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for SegmentationIdentifier.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SegmentationIdentifier">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Binary"/>
 *     &lt;enumeration value="Fractional_Probability"/>
 *     &lt;enumeration value="Fractional_Occupancy"/>
 *     &lt;enumeration value="Surface"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum SegmentationIdentifier {

    @XmlEnumValue("Binary")
    BINARY("Binary"),
    @XmlEnumValue("Fractional_Probability")
    FRACTIONAL_PROBABILITY("Fractional_Probability"),
    @XmlEnumValue("Fractional_Occupancy")
    FRACTIONAL_OCCUPANCY("Fractional_Occupancy"),
    @XmlEnumValue("Surface")
    SURFACE("Surface");
    private final String value;

    SegmentationIdentifier(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SegmentationIdentifier fromValue(String v) {
        for (SegmentationIdentifier c: SegmentationIdentifier.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
